### ISSUE TITLE
Number of parameters do not match

### ISSUE THREAD

**Issue by yashbhalgat** [romulus0914/MixNet-Pytorch#2]
The number of parameters in your model are very different from the ones in the paper (please correct me if I am wrong).
You can reproduce this simply by running the following:
```
from mixnet import MixNet
model = MixNet(net_type="mixnet_m")
num_params = sum(p.numel() for p in model.parameters())
print(num_params)
```

MixNet_m should have 5.01M parameters. But this gives me 10.63M parameters. Can you please rectify this?

Thanks!

**Comment by romulus0914** [comment]
Hi, thanks for pointing out this problem.
However, I do not have the answer to it right now.
Please let me know if any implementation in repo is incorrect.
Thanks again!

**Comment by liangxiao05** [comment]
Updated.
Thanks for your work, I use the newest codes ,still some differences:
mixnet_s  (without SE):
flops:353M,params:3.8M
mixnet_m (without SE):
flops:499M,params:4.6M
I test it like this:
```
net=MixNet()
from thop import profile
input = torch.randn(1,3,224,224)
flops,params=profile(net,inputs=(input,))
```

**Comment by romulus0914** [comment]
I'm not sure if it is the case. I've tried to count #parameters w/o any "squeeze and excite" layers, and the results are quite similar to the number reported in the paper.

**Comment by romulus0914** [comment]
Hi @yashbhalgat and @liangxiao05 
I finally found the errors. There are two errors in the code. One is minor, and the other is the major problem.

First, I neglected the "Grouped Convolution" used in the official repo and considered it same as the normal "Conv2d". However, I found out that they are actually "grouped" convolution in the "expansion phase" and "projection phase" of MixDepthwiseConv. Therefore, using normal convolution would lead to a little bit increment on #params.

Second, the major issue is in "Squeeze and Excite layer". The squeezed channels are mistakenly calculated by the channels "after" expansion phase, however it should be calculated based on the channels "before" the expansion phase. This incorrect implementation increases lots of params.

Please inform me if there are more errors in the repo. Thx!
