### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by yashbhalgat** [romulus0914/MixNet-Pytorch#3]
Hi,
Do you plan to release pretrained models for MixNet? It would be a great help. :)
Thanks

**Comment by ansleliu** [comment]
@yashbhalgat you can download all mixnet pre-trained weights from this repo.: [https://github.com/ansleliu/MixNet-Pytorch](https://github.com/ansleliu/MixNet-Pytorch)

**Comment by yashbhalgat** [comment]
Thanks @ansleliu. But I was able to get the pretrained model from https://github.com/rwightman/gen-efficientnet-pytorch and then convert the checkpoint keys to match the model.py file. :)
