### ISSUE TITLE
MixNet structure 

### ISSUE THREAD

**Issue by xdg2016** [romulus0914/MixNet-Pytorch#7]
![image](https://user-images.githubusercontent.com/16351823/68447725-ece49f80-021b-11ea-918e-218b2155dc09.png)
Hello, I find the parameters of net structure in your code is  different from the structure in paper, can you tell me why?

**Comment by romulus0914** [comment]
Hi,

Can you be more specific about which part of the structure?

Thanks

**Comment by xdg2016** [comment]
Thanks for your reply
1、 I run your mixnet.py and print the feature map size of each mixblock as follow:
MixNetBlock
MixNetBlock input size: torch.Size([1, 16, 112, 112])
MixNetBlock output size: torch.Size([1, 16, 112, 112])

MixNetBlock input size: torch.Size([1, 16, 112, 112])
MixNetBlock output size: torch.Size([1, 24, 56, 56])

MixNetBlock input size: torch.Size([1, 24, 56, 56])
MixNetBlock output size: torch.Size([1, 24, 56, 56])

MixNetBlock input size: torch.Size([1, 24, 56, 56])
MixNetBlock output size: torch.Size([1, 40, 28, 28])

MixNetBlock input size: torch.Size([1, 40, 28, 28])
MixNetBlock output size: torch.Size([1, 40, 28, 28])

MixNetBlock input size: torch.Size([1, 40, 28, 28])
MixNetBlock output size: torch.Size([1, 40, 28, 28])

MixNetBlock input size: torch.Size([1, 40, 28, 28])
MixNetBlock output size: torch.Size([1, 40, 28, 28])

MixNetBlock input size: torch.Size([1, 40, 28, 28])
MixNetBlock output size: torch.Size([1, 80, 14, 14])

MixNetBlock input size: torch.Size([1, 80, 14, 14])
MixNetBlock output size: torch.Size([1, 80, 14, 14])

MixNetBlock input size: torch.Size([1, 80, 14, 14])
MixNetBlock output size: torch.Size([1, 80, 14, 14])

MixNetBlock input size: torch.Size([1, 80, 14, 14])
MixNetBlock output size: torch.Size([1, 120, 14, 14])

MixNetBlock input size: torch.Size([1, 120, 14, 14])
MixNetBlock output size: torch.Size([1, 120, 14, 14])

MixNetBlock input size: torch.Size([1, 120, 14, 14])
MixNetBlock output size: torch.Size([1, 120, 14, 14])

MixNetBlock input size: torch.Size([1, 120, 14, 14])
MixNetBlock output size: torch.Size([1, 200, 7, 7])

MixNetBlock input size: torch.Size([1, 200, 7, 7])
MixNetBlock output size: torch.Size([1, 200, 7, 7])

MixNetBlock input size: torch.Size([1, 200, 7, 7])
MixNetBlock output size: torch.Size([1, 200, 7, 7])
#----------------------------------------------------------
however the feature map size of the 8th,9th,10th Mixblock is [14 x14], I check the fig in paper, feature map size in these blocks is [28x28].
![image](https://user-images.githubusercontent.com/16351823/68467019-72824280-0250-11ea-90ba-71b69ce9f959.png)

2、The kernels in 12th and 13th mmixed_depthwise_conv are [3,5,7] in fig, but in your code, they are [3,5,7,9]
![image](https://user-images.githubusercontent.com/16351823/68467204-c0974600-0250-11ea-94f1-36e7868e9407.png)

![image](https://user-images.githubusercontent.com/16351823/68467136-a8272b80-0250-11ea-87a8-0ce54a9887fc.png)
maybe you are right, I check the official code implemented with tensorflow, thier config is same to yours.

**Comment by romulus0914** [comment]
Hi,

I did not notice it before. Thanks for your carefulness.
Since I set up the these parameters by taking the official config as reference, I suggest we follow it for now.

Thanks
